### ISSUE TITLE
Problem of Dimension Incompatibility when using Auto-PGD

### ISSUE THREAD

**Issue by taylover2016** [Trusted-AI/adversarial-robustness-toolbox#943] opened 2021-03-07 04:38 UTC
**Describe the bug**
Hi there. I've successfully implement the FGM attack to my test set.
But when I turn to Auto-PGD, there seems to have a problem.
Applying Auto-PGD will automatically add one to the dimensionality,
leading to the dimension incompatibility when nn.module is receiving the input.

**To Reproduce**

The test set is a set of 40 photos with only 1 channel, height of 57 and width of 47.
The model is pretrained, and the prediction on the original set is fine.

But when applying AutoProjectedGradientDescent() method, an error is raised:
"RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 1, 5, 5], but got 5-dimensional input of size [1, 40, 1, 57, 47] instead"

I looked into the source code and noted that the corresponding line is 
"estimator.predict(x=np.ones(shape=(1, *estimator.input_shape), dtype=np.float32))"
seems it just automatically add a "1" prefix to it.

Is there any way to solve it?

**System information (please complete the following information):**
 - macOS 11.2.2
 - Python 3.8.8
 - ART version 1.5.2
 - PyTorch 1.8.0

**Comment by taylover2016** [comment] 2021-03-07 07:02
And as a plus, it's the same when I apply the BrendelBethge attack. I wonder what is the purpose of doing so🧐

**Comment by beat-buesser** [comment] 2021-03-08 11:05
Hi @taylover2016 Thank you very much for exploring ART. Could you please provide a reproducible example in a Google Colab notebook?

**Comment by beat-buesser** [comment] 2021-03-08 12:42
My first guess would be to take a closer look at the definition of you estimator's input_shape argument.

**Comment by taylover2016** [comment] 2021-03-08 13:56
Well, due to some network conditions, I can't get access to the Google CoLab:(
Can I send the code to you someway? Or maybe I'll upload it to my homepage so it's easier.
Anyway, thx for the reply. It really means a lot.😁

**Comment by taylover2016** [comment] 2021-03-08 13:56
Well, due to some network conditions, I can't get access to the Google CoLab:(
Can I send the code to you someway? Or maybe I'll upload it together with the code for other questions to my homepage so it's easier.
Anyway, thx for the reply. It really means a lot.😁

**Comment by beat-buesser** [comment] 2021-03-08 17:39
@taylover2016 Ok, I see. I think you also can share jupyter notebook files here by dragging and dropping them into the comment window below. Otherwise you also can paste the code of the example into the comment window and link an example image or refer to a dataset e.g. ImageNet that I can access to reproduce your results.

**Comment by taylover2016** [comment] 2021-03-09 03:20
@beat-buesser Thx for the advice. I've uploaded it to my repo, and here's the link<https://github.com/taylover2016/For_ART_Test>. The "ART_attack.py" is the main file, and the dataset is "olivettifaces.gif". The params for the model is uploaded as well and is loaded in the "ART_attack.py" file.
The code in it may be a little messy though, cuz I'm still in the testing process. All the attacks are built in together, and they're separated with the comments. It may take some efforts for you to switch between White-Box and Black-Box, different attacks, etc. Because I've integrated the code for several different issues.
Again, thx a lot for the reply, this really means a lot to me.

**Comment by taylover2016** [comment] 2021-03-09 03:56
@beat-buesser I've checked my estimator's input_shape, which is [40, 1, 57, 47], the same as defined in the PyTorch model.
In the PyTorchClassifier definition, I pass in the param as "input_shape=data.shape", where data is the input for the model.
This definition works fine with other attacks such as PGD and CW. So I wonder why would such an error occur when it comes to Auto-PGD.

**Comment by beat-buesser** [comment] 2021-03-09 11:25
Hi @taylover2016 Thank you very much for providing a full example, this will make it much easier to provide support. The first issue I notice is that `input_shape` has to be the shape of a single sample and not the shape of a batch of samples because the batch size can changes.

Could you please try changing `ART_attack.py` in [L145](https://github.com/taylover2016/For_ART_Test/blob/c030e4de76dfb71c78002d7694165b683a41b212/ART_attack.py#L145)  to `input_shape=data[0].shape,`?

For this dataset, the value provided to `input_shape` should be `(1, 57, 47)`.

**Comment by beat-buesser** [comment] 2021-03-09 15:04
Hi @taylover2016 That's great news! I'll close this issue then, but feel free to reopen if you have more questions.

**Closed by beat-buesser** 2021-03-09 15:04 UTC
Labels: question
