### ISSUE TITLE
BoundaryAttack (and maybe HopSkipJump) might not find/return optimal adv. example

### ISSUE THREAD

**Issue by beat-buesser** [Trusted-AI/adversarial-robustness-toolbox#923] opened 2021-03-01 21:10 UTC
**Describe the bug**
We are currently investigating if `BoundaryAttack` (and maybe also `HopSkipJump`) are returning the optimal adversarial examples that could be found. We are also investigating their support for untargeted and targeted attacks.

Thank you @amodas for discovering and investigating this issue!

**Comment by amodas** [comment] 2021-03-04 11:28
Thank you @beat-buesser for opening this! I can be more specific regarding my observations/recommendations.

I will start with [`BoundaryAttack`](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/evasion/boundary.py) for now. I have not spent much time on `HopSkipJump` yet, but once I do, I will check if similar parts can also be improved, and then will create a different post here.

Please, **read my suggestions carefully** in case I have some problem/error in my reasoning and/or observations! Thanks!

## Issue 1: BoundaryAttack is not properly treating targeted and untargeted cases

Inside the `_attack()` method the algorithm checks which of the predictions satisfy the adversarial criterion, and based on this check it computes the delta ratio and the epsilon ratio for the adversarial candidates.

However, in the current implementation, both for the delta ratio ([link](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/4ca921bb336ec596a8e44f2d5b699df8fbaa9ae9/art/attacks/evasion/boundary.py#L251)) and the epsilon ratio ([link](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/4ca921bb336ec596a8e44f2d5b699df8fbaa9ae9/art/attacks/evasion/boundary.py#L273)) the algorithm just checks
```
satisfied = preds == target
```
which is a criterion that makes sense **only for targeted attacks**. As a minimal example, consider an **untargetd** attack. The algorithm will initially compute a random adversarial image that has some label `label_rand`, which corresponds to `initial_sample[1]` of line 200 ([link](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/4ca921bb336ec596a8e44f2d5b699df8fbaa9ae9/art/attacks/evasion/boundary.py#L200)). This `initial_sample[1]` is passed as the `target` argument of the `_attack()` method, and then the algorithm will select the adversarial candidates based on the adversarial criterion
```
satisfied = preds == target
```
In other words, it will always consider only the adversarial candidates that have the same label as `label_rand`. This is in fact **a targeted** attack with a semi-randomly chosen target.

Having a proper `untargeted` attack is very simple, and is based on the adversarial criterion that we want to select those adversarial candidates that have a different label than the label of the original image (by definition of adversarial). In the implementation, the predicted label of the original image is denoted as `y_p` (see line 157 and 167 where it is passed as an argument to the `_perturb()` method of line 184).

**Suggested fix**:
1. Pass `y_p` as an argument to `_attack()` (line 211)
2. Change the adversarial criteria for updating delta ratio (line 251) and epsilon ratio (line 273) from `satisfied = preds == target` to:
```
if self.targeted:
    satisfied = preds == target
else:
    satisfied = preds != y_p
```

## Issue 2: BoundaryAttack does not return the "optimal" adversarial example

Within an iteration of `BoundaryAttack`, the current implementation selects the final/running adversarial example/update `x_adv` as
```
if epsilon_ratio > 0:
   x_adv = potential_advs[np.where(satisfied)[0][0]]
   self.curr_adv = x_adv
   break
```
and then continues to the next iteration (see [this](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/4ca921bb336ec596a8e44f2d5b699df8fbaa9ae9/art/attacks/evasion/boundary.py#L281) code block). 

However, `x_adv = potential_advs[np.where(satisfied)[0][0]]` does not satisfy any "optimal" criterion, since it **just selects the first adversarial candidate out of all the possible adversarial candidates**. In fact, `x_adv` should be the one that, out of all the candidates, has the minimum L2 distance from the original image, since one of the objectives of `BoundaryAttack` is to find a minimal (in an L2-norm sense) adversarial example.

**Suggested fix**:
This can be easily fixed by implementing a method that, out of all the candidates, it finds the one that has the minimum L2 distance from the original image. Below is a suggestion of such a method

```
@staticmethod
def _best_adv(original_sample, candidates):
    shape = candidates.shape
    min_idx = np.linalg.norm(original_sample.flatten() - candidates.reshape(shape[0], -1), axis=1).argmin()
    return candidates[min_idx]
```

This method can then be called in the code (as a replacement of [this](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/4ca921bb336ec596a8e44f2d5b699df8fbaa9ae9/art/attacks/evasion/boundary.py#L281) code block) as follows:

```
if epsilon_ratio > 0:
   x_adv = self._best_adv(original_sample, potential_advs[np.where(satisfied)[0]])
   self.curr_adv = x_adv
   break
```

## Issue 3: BoundaryAttack does not return the proper adversarial example when it finds a suboptimal solution

In some cases, `BoundaryAttack` might not be able to find an optimal adversarial example. Such cases can happen if repeatedly all the adversarial candidates computed after the `delta` step (line [262](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/4ca921bb336ec596a8e44f2d5b699df8fbaa9ae9/art/attacks/evasion/boundary.py#L262)) or after the `epsilon` step (line [285](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/4ca921bb336ec596a8e44f2d5b699df8fbaa9ae9/art/attacks/evasion/boundary.py#L285)) do not fool the classifier.

The case of `delta` (line [262](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/4ca921bb336ec596a8e44f2d5b699df8fbaa9ae9/art/attacks/evasion/boundary.py#L262)) is treated properly, since the latest adversarial example `x_adv` is returned (although here one could also return the `self.curr_adv`).

However, the case of `epsilon` is not treated properly! In fact the current implementation just returns `x_advs[0]` as seen in line [287](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/4ca921bb336ec596a8e44f2d5b699df8fbaa9ae9/art/attacks/evasion/boundary.py#L287). Note that `x_advs` are the potential adversarial candidates computed after the `delta` step. Hence, and related to Issue 2, the algorithm should not just return the first element of these candidates (`x_advs[0]`) but should rather return the one that has the minimum L2 distance from the original image.

**Suggested fix**:
This can be easily fixed by using the method introduced in Issue 2. Hence, line [287](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/4ca921bb336ec596a8e44f2d5b699df8fbaa9ae9/art/attacks/evasion/boundary.py#L287) should just be replaced by
```
return self._best_adv(original_sample, x_advs)
```

## Issue 4 (not exactly): Computation of orthogonal perturbation can be speeded up

During the delta update step, the current implementation generates a set of adversarial candidates by computing the orthogonal perturbation (see lines 244 to 248). This is done in a for-loop way (looped over `self.sample_size`). However, the for-loop is unnecessary since everything can be done in a tensor/batch way inside the `_orthogonal_perturb()` method. 

**Suggested fix**:
Below you can find an alternative implementation of `_orthogonal_perturb()` that computes the exact same thing as the current implementation, but generates a batch of adversarial candidates directly. In practice, the main conceptual difference in the following implementations is that, instead of computing **a single** random perturbation, it computes **multiple** random perturbations of batch dimension `self.sample_size`:

```
def _orthogonal_perturb(self, delta: float, current_sample: np.ndarray, original_sample: np.ndarray) -> np.ndarray:
    """
    Create multiple orthogonal perturbations.

    :param delta: Initial step size for the orthogonal step.
    :param current_sample: Current adversarial example.
    :param original_sample: The original input.
    :return: a set of possible perturbations.
    """

    # Generate perturbation randomly
    # perturb = np.random.randn(*self.estimator.input_shape).astype(ART_NUMPY_DTYPE)  # old version
    perturb = np.random.randn(*((self.sample_size,) + self.estimator.input_shape)).astype(ART_NUMPY_DTYPE)  # new batch version

    # Rescale the perturbation
    # perturb /= np.linalg.norm(perturb)  # old version
    unit_shape = (perturb.shape[0],) + tuple([1 for _ in range(len(perturb.shape[1:]))])  # new batch version
    perturb /= np.linalg.norm(perturb.reshape(unit_shape[0], -1), axis=1).reshape(unit_shape)  # new batch version

    perturb *= delta * np.linalg.norm(original_sample - current_sample)

    # Project the perturbation onto sphere
    direction = original_sample - current_sample

    # direction_flat = direction.flatten()  # old version
    # perturb_flat = perturb.flatten()  # old version
    direction_flat = direction.reshape(1, -1)  # new batch version
    perturb_flat = perturb.reshape(perturb.shape[0], -1)  # new batch version

    direction_flat /= np.linalg.norm(direction_flat)
    perturb_flat -= np.dot(perturb_flat, direction_flat.T) * direction_flat
    # perturb = perturb_flat.reshape(self.estimator.input_shape)  # old version
    perturb = perturb_flat.reshape(perturb.shape)  # new batch version

    hypotenuse = np.sqrt(1 + delta ** 2)
    perturb = ((1 - hypotenuse) * (current_sample - original_sample) + perturb) / hypotenuse
    return perturb
```

Hence, the code block of lines 244 to 248 with the for loop 
```
potential_advs = []
for _ in range(self.sample_size):
    potential_adv = x_adv + self._orthogonal_perturb(self.curr_delta, x_adv, original_sample)
    potential_adv = np.clip(potential_adv, clip_min, clip_max)
    potential_advs.append(potential_adv)
```
can be replaced by the following code block:
```
potential_advs = x_adv + self._orthogonal_perturb(self.curr_delta, x_adv, original_sample)
potential_advs = np.clip(potential_advs, clip_min, clip_max)
```

**Comment by beat-buesser** [comment] 2021-03-04 14:36
@amodas Thank you very much! This is an amazing analysis and I'm convinced that these updates will make `BoundaryAttack` much stronger and more efficient!

**Comment by amodas** [comment] 2021-03-08 10:44
Some results for **Issue 1: BoundaryAttack is not properly treating targeted and untargeted cases**. As you can see, the improvement is significant compared to the previous version. Also, note how the predicted adversarial label changes (in contrast to the previous version).

```python
global_seed = 999

import sys
sys.path.append('./adversarial-robustness-toolbox')

import imagenet_stubs
import numpy as np
import torch
import torch.nn as nn
import torchvision.models as models
import torchvision.transforms as transforms
import random

import os
os.environ['PYTHONHASHSEED'] = str(global_seed)

from matplotlib import pyplot as plt
from PIL import Image

from art.estimators.classification import PyTorchClassifier
from art.attacks.evasion import BoundaryAttack
```

### Set determinism for reproducibility


```python
def set_global_seed(seed):
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.manual_seed(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True
```

### Load Torchvision model


```python
model = models.resnet18(pretrained=True).eval()

mean = np.asarray((0.485, 0.456, 0.406), dtype=np.float32).reshape((1, 3, 1, 1))
std = np.asarray((0.229, 0.224, 0.225), dtype=np.float32).reshape((1, 3, 1, 1))

classifier = PyTorchClassifier(
    model=model,
    clip_values=(0.0, 1.0),
    input_shape=(3, 224, 224),
    nb_classes=1000,
    use_amp=False,
    preprocessing=(mean, std),
    channels_first=True,
    loss=nn.CrossEntropyLoss()
)
```

### Define image transformation


```python
def tf(x):
    x = np.expand_dims(x, axis=0)
    return np.transpose(x, (0, 3, 1, 2))
```

### Load image


```python
original_image_name = 'standard_poodle.jpg'
for image_path in imagenet_stubs.get_image_paths():
    if image_path.endswith(original_image_name):
        original_image = Image.open(image_path)
        original_image = original_image.resize((224, 224))
        original_image = np.array(original_image) / 255.0
        original_image = original_image.astype(np.float32)

original_label = np.argmax(classifier.predict(tf(original_image)), axis=1)[0]
print("\nOriginal label is: %d\n" % original_label)

plt.imshow(original_image)
plt.show()
```

    
    Original label is: 267
   
![output_8_1](https://user-images.githubusercontent.com/25585560/110311108-a1a2f280-8003-11eb-96f3-96fb4a84f004.png) 


### BoundaryAttack parameters


```python
max_iterations = 1000
delta = 0.01
epsilon = 0.01
targeted = False

iter_step = 50
```

### BoundaryAttack before fixing the targeted/untargeted adversarial check


```python
set_global_seed(global_seed)
use_modification = False

attack = BoundaryAttack(estimator=classifier,
                        targeted=targeted,
                        max_iter=0,
                        delta=delta,
                        epsilon=epsilon,
                        verbose=False,
                        use_modification=use_modification)

attack.rng = np.random.default_rng(seed=global_seed)

x_adv = None
for i in range(int(max_iterations / iter_step) + 1):
    x_adv = attack.generate(x=tf(original_image), x_adv_init=x_adv)

    #clear_output()
    L2_err = np.linalg.norm(x_adv[0] - tf(original_image)[0])
    pred_label = np.argmax(classifier.predict(x_adv)[0])
    
    if i == 0:
        print("[Init (rnd)] \t L2 error: %.2f \t | \t Class label: %d" % (L2_err,
                                                                           pred_label))
    else:
        print("[Iter %d] \t L2 error: %.2f \t | \t Class label: %d" % (i * iter_step,
                                                                    L2_err,
                                                                    pred_label))
    
    if hasattr(attack, 'curr_delta') and hasattr(attack, 'curr_epsilon'):
        attack.max_iter = iter_step 
        attack.delta = attack.curr_delta
        attack.epsilon = attack.curr_epsilon
    else:
        break
```

    [Init (rnd)] 	 L2 error: 151.05 	 | 	 Class label: 107
    [Iter 50] 	 L2 error: 90.13 	 | 	 Class label: 107
    [Iter 100] 	 L2 error: 84.27 	 | 	 Class label: 107
    [Iter 150] 	 L2 error: 78.92 	 | 	 Class label: 107
    [Iter 200] 	 L2 error: 71.42 	 | 	 Class label: 107
    [Iter 250] 	 L2 error: 65.56 	 | 	 Class label: 107
    [Iter 300] 	 L2 error: 60.66 	 | 	 Class label: 107
    [Iter 350] 	 L2 error: 55.42 	 | 	 Class label: 107
    [Iter 400] 	 L2 error: 50.90 	 | 	 Class label: 107
    [Iter 450] 	 L2 error: 47.86 	 | 	 Class label: 107
    [Iter 500] 	 L2 error: 45.06 	 | 	 Class label: 107
    [Iter 550] 	 L2 error: 43.16 	 | 	 Class label: 107
    [Iter 600] 	 L2 error: 41.19 	 | 	 Class label: 107
    [Iter 650] 	 L2 error: 39.18 	 | 	 Class label: 107
    [Iter 700] 	 L2 error: 37.34 	 | 	 Class label: 107
    [Iter 750] 	 L2 error: 36.15 	 | 	 Class label: 107
    [Iter 800] 	 L2 error: 34.91 	 | 	 Class label: 107
    [Iter 850] 	 L2 error: 33.46 	 | 	 Class label: 107
    [Iter 900] 	 L2 error: 32.56 	 | 	 Class label: 107
    [Iter 950] 	 L2 error: 31.16 	 | 	 Class label: 107
    [Iter 1000] 	 L2 error: 30.02 	 | 	 Class label: 107


### BoundaryAttack after fixing the targeted/untargeted adversarial check


```python
set_global_seed(global_seed)
use_modification = True

attack = BoundaryAttack(estimator=classifier,
                        targeted=targeted,
                        max_iter=0,
                        delta=delta,
                        epsilon=epsilon,
                        verbose=False,
                        use_modification=use_modification)

attack.rng = np.random.default_rng(seed=global_seed)

x_adv = None
for i in range(int(max_iterations / iter_step) + 1):
    x_adv = attack.generate(x=tf(original_image), x_adv_init=x_adv)

    #clear_output()
    L2_err = np.linalg.norm(x_adv[0] - tf(original_image)[0])
    pred_label = np.argmax(classifier.predict(x_adv)[0])
    
    if i == 0:
        print("[Init (rnd)] \t L2 error: %.2f \t | \t Class label: %d" % (L2_err,
                                                                           pred_label))
    else:
        print("[Iter %d] \t L2 error: %.2f \t | \t Class label: %d" % (i * iter_step,
                                                                    L2_err,
                                                                    pred_label))
    
    if hasattr(attack, 'curr_delta') and hasattr(attack, 'curr_epsilon'):
        attack.max_iter = iter_step 
        attack.delta = attack.curr_delta
        attack.epsilon = attack.curr_epsilon
    else:
        break
```

    [Init (rnd)] 	 L2 error: 151.05 	 | 	 Class label: 107
    [Iter 50] 	 L2 error: 27.55 	 | 	 Class label: 183
    [Iter 100] 	 L2 error: 17.69 	 | 	 Class label: 183
    [Iter 150] 	 L2 error: 12.42 	 | 	 Class label: 183
    [Iter 200] 	 L2 error: 9.39 	 | 	 Class label: 183
    [Iter 250] 	 L2 error: 7.21 	 | 	 Class label: 183
    [Iter 300] 	 L2 error: 6.25 	 | 	 Class label: 183
    [Iter 350] 	 L2 error: 5.54 	 | 	 Class label: 183
    [Iter 400] 	 L2 error: 4.90 	 | 	 Class label: 183
    [Iter 450] 	 L2 error: 4.49 	 | 	 Class label: 183
    [Iter 500] 	 L2 error: 4.10 	 | 	 Class label: 183
    [Iter 550] 	 L2 error: 3.78 	 | 	 Class label: 183
    [Iter 600] 	 L2 error: 3.54 	 | 	 Class label: 183
    [Iter 650] 	 L2 error: 3.29 	 | 	 Class label: 183
    [Iter 700] 	 L2 error: 3.10 	 | 	 Class label: 183
    [Iter 750] 	 L2 error: 2.99 	 | 	 Class label: 183
    [Iter 800] 	 L2 error: 2.84 	 | 	 Class label: 183
    [Iter 850] 	 L2 error: 2.74 	 | 	 Class label: 183
    [Iter 900] 	 L2 error: 2.63 	 | 	 Class label: 183
    [Iter 950] 	 L2 error: 2.53 	 | 	 Class label: 183
    [Iter 1000] 	 L2 error: 2.43 	 | 	 Class label: 183

**Comment by amodas** [comment] 2021-03-08 10:48
Some results related to **Issue2** and **Issue3**. As you can see the improvement is not significant, but still the final L2 norm is slightly smaller. This makes sense since all the sampled adversarial candidates are very close to each other, hence the L2 norm from the original image should be roughly the same, Note though that his effect might be stronger when applied on another image, or some non-trivial geometric situations occur. Nevertheless, it seems like a proper criterion for having as the default.

```python
global_seed = 999

import sys
sys.path.append('./adversarial-robustness-toolbox')

import imagenet_stubs
import numpy as np
import torch
import torch.nn as nn
import torchvision.models as models
import torchvision.transforms as transforms
import random

import os
os.environ['PYTHONHASHSEED'] = str(global_seed)

from matplotlib import pyplot as plt
from PIL import Image

from art.estimators.classification import PyTorchClassifier
from art.attacks.evasion import BoundaryAttack
```

### Set determinism for reproducibility


```python
def set_global_seed(seed):
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.manual_seed(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True
```

### Load Torchvision model


```python
model = models.resnet18(pretrained=True).eval()

mean = np.asarray((0.485, 0.456, 0.406), dtype=np.float32).reshape((1, 3, 1, 1))
std = np.asarray((0.229, 0.224, 0.225), dtype=np.float32).reshape((1, 3, 1, 1))

classifier = PyTorchClassifier(
    model=model,
    clip_values=(0.0, 1.0),
    input_shape=(3, 224, 224),
    nb_classes=1000,
    use_amp=False,
    preprocessing=(mean, std),
    channels_first=True,
    loss=nn.CrossEntropyLoss()
)
```

### Define image transformation


```python
def tf(x):
    x = np.expand_dims(x, axis=0)
    return np.transpose(x, (0, 3, 1, 2))
```

### Load image


```python
original_image_name = 'standard_poodle.jpg'
for image_path in imagenet_stubs.get_image_paths():
    if image_path.endswith(original_image_name):
        original_image = Image.open(image_path)
        original_image = original_image.resize((224, 224))
        original_image = np.array(original_image) / 255.0
        original_image = original_image.astype(np.float32)

original_label = np.argmax(classifier.predict(tf(original_image)), axis=1)[0]
print("\nOriginal label is: %d\n" % original_label)

plt.imshow(original_image)
plt.show()
```

    
    Original label is: 267
    

![output_8_1](https://user-images.githubusercontent.com/25585560/110311458-18d88680-8004-11eb-83af-9a8e7d3a870e.png)

    


### BoundaryAttack parameters


```python
max_iterations = 1000
delta = 0.01
epsilon = 0.01
targeted = False

iter_step = 50
```

### BoundaryAttack before fixing the min L2 criterion (targeted/untargeted already fixed)


```python
set_global_seed(global_seed)
use_modification = False

attack = BoundaryAttack(estimator=classifier,
                        targeted=targeted,
                        max_iter=0,
                        delta=delta,
                        epsilon=epsilon,
                        verbose=False,
                        use_modification=use_modification)

attack.rng = np.random.default_rng(seed=global_seed)

x_adv = None
for i in range(int(max_iterations / iter_step) + 1):
    x_adv = attack.generate(x=tf(original_image), x_adv_init=x_adv)

    #clear_output()
    L2_err = np.linalg.norm(x_adv[0] - tf(original_image)[0])
    pred_label = np.argmax(classifier.predict(x_adv)[0])
    
    if i == 0:
        print("[Init (rnd)] \t L2 error: %.2f \t | \t Class label: %d" % (L2_err,
                                                                           pred_label))
    else:
        print("[Iter %d] \t L2 error: %.2f \t | \t Class label: %d" % (i * iter_step,
                                                                    L2_err,
                                                                    pred_label))
    
    if hasattr(attack, 'curr_delta') and hasattr(attack, 'curr_epsilon'):
        attack.max_iter = iter_step 
        attack.delta = attack.curr_delta
        attack.epsilon = attack.curr_epsilon
    else:
        break
```

    [Init (rnd)] 	 L2 error: 151.05 	 | 	 Class label: 107
    [Iter 50] 	 L2 error: 27.55 	 | 	 Class label: 183
    [Iter 100] 	 L2 error: 17.69 	 | 	 Class label: 183
    [Iter 150] 	 L2 error: 12.42 	 | 	 Class label: 183
    [Iter 200] 	 L2 error: 9.39 	 | 	 Class label: 183
    [Iter 250] 	 L2 error: 7.21 	 | 	 Class label: 183
    [Iter 300] 	 L2 error: 6.25 	 | 	 Class label: 183
    [Iter 350] 	 L2 error: 5.54 	 | 	 Class label: 183
    [Iter 400] 	 L2 error: 4.90 	 | 	 Class label: 183
    [Iter 450] 	 L2 error: 4.49 	 | 	 Class label: 183
    [Iter 500] 	 L2 error: 4.10 	 | 	 Class label: 183
    [Iter 550] 	 L2 error: 3.78 	 | 	 Class label: 183
    [Iter 600] 	 L2 error: 3.54 	 | 	 Class label: 183
    [Iter 650] 	 L2 error: 3.29 	 | 	 Class label: 183
    [Iter 700] 	 L2 error: 3.10 	 | 	 Class label: 183
    [Iter 750] 	 L2 error: 2.99 	 | 	 Class label: 183
    [Iter 800] 	 L2 error: 2.84 	 | 	 Class label: 183
    [Iter 850] 	 L2 error: 2.74 	 | 	 Class label: 183
    [Iter 900] 	 L2 error: 2.63 	 | 	 Class label: 183
    [Iter 950] 	 L2 error: 2.53 	 | 	 Class label: 183
    [Iter 1000] 	 L2 error: 2.43 	 | 	 Class label: 183


### BoundaryAttack after fixing the min L2 criterion (targeted/untargeted already fixed)


```python
set_global_seed(global_seed)
use_modification = True

attack = BoundaryAttack(estimator=classifier,
                        targeted=targeted,
                        max_iter=0,
                        delta=delta,
                        epsilon=epsilon,
                        verbose=False,
                        use_modification=use_modification)

attack.rng = np.random.default_rng(seed=global_seed)

x_adv = None
for i in range(int(max_iterations / iter_step) + 1):
    x_adv = attack.generate(x=tf(original_image), x_adv_init=x_adv)

    #clear_output()
    L2_err = np.linalg.norm(x_adv[0] - tf(original_image)[0])
    pred_label = np.argmax(classifier.predict(x_adv)[0])
    
    if i == 0:
        print("[Init (rnd)] \t L2 error: %.2f \t | \t Class label: %d" % (L2_err,
                                                                           pred_label))
    else:
        print("[Iter %d] \t L2 error: %.2f \t | \t Class label: %d" % (i * iter_step,
                                                                    L2_err,
                                                                    pred_label))
    
    if hasattr(attack, 'curr_delta') and hasattr(attack, 'curr_epsilon'):
        attack.max_iter = iter_step 
        attack.delta = attack.curr_delta
        attack.epsilon = attack.curr_epsilon
    else:
        break
```

    [Init (rnd)] 	 L2 error: 151.05 	 | 	 Class label: 107
    [Iter 50] 	 L2 error: 29.31 	 | 	 Class label: 183
    [Iter 100] 	 L2 error: 21.10 	 | 	 Class label: 183
    [Iter 150] 	 L2 error: 14.83 	 | 	 Class label: 183
    [Iter 200] 	 L2 error: 10.65 	 | 	 Class label: 183
    [Iter 250] 	 L2 error: 8.19 	 | 	 Class label: 183
    [Iter 300] 	 L2 error: 6.72 	 | 	 Class label: 183
    [Iter 350] 	 L2 error: 5.49 	 | 	 Class label: 183
    [Iter 400] 	 L2 error: 4.75 	 | 	 Class label: 183
    [Iter 450] 	 L2 error: 4.31 	 | 	 Class label: 183
    [Iter 500] 	 L2 error: 3.94 	 | 	 Class label: 183
    [Iter 550] 	 L2 error: 3.67 	 | 	 Class label: 183
    [Iter 600] 	 L2 error: 3.42 	 | 	 Class label: 183
    [Iter 650] 	 L2 error: 3.22 	 | 	 Class label: 183
    [Iter 700] 	 L2 error: 3.04 	 | 	 Class label: 183
    [Iter 750] 	 L2 error: 2.89 	 | 	 Class label: 183
    [Iter 800] 	 L2 error: 2.76 	 | 	 Class label: 183
    [Iter 850] 	 L2 error: 2.65 	 | 	 Class label: 183
    [Iter 900] 	 L2 error: 2.55 	 | 	 Class label: 183
    [Iter 950] 	 L2 error: 2.44 	 | 	 Class label: 183
    [Iter 1000] 	 L2 error: 2.35 	 | 	 Class label: 183

**Comment by amodas** [comment] 2021-03-16 10:34
After spending some time on `HopSkipJump` as well, I think that the implementation is taking care of the criteria and requirements. That is, we do not have issues similar to `BoundaryAttack` in terms of sub-optimality. Unless, of course, if I'm missing something. 

@beat-buesser Since BA has been fixed/merged, and HSJ seems legit, maybe we can close this issue?

**Comment by beat-buesser** [comment] 2021-03-16 11:07
Hi @amodas Thank you very much for your amazing and very detailed analysis of `BoundaryAttack` and `HopSkipJump` which made ART's boundary attack much more accurate and efficient!

I'll schedule the issue to close with today's 1.6.0 release of these upgrades.

**Closed** 2021-03-16 17:58 UTC
Labels: improvement
